package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* piątek, 3 września 2021 16:57:02 CEST
*/

public interface EchoOperations 
{
  int PIK_OtworzSesje(org.omg.CORBA.portable.InputStream in);
  int PIK_WybierzSerwer(org.omg.CORBA.portable.InputStream in);
  int PIK_SprawdzSerwer(org.omg.CORBA.portable.InputStream in);
  String PIK_ZeZmiennej(org.omg.CORBA.portable.InputStream in);
} // interface EchoOperations
