package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* piątek, 3 września 2021 16:57:02 CEST
*/

public interface EchoOperations 
{
  String echoString ();
} // interface EchoOperations
